# Generated by Django 4.2.9 on 2024-08-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraped_data',
            name='age_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraped_data',
            name='first_scraped_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
