# Generated by Django 4.2.9 on 2024-08-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0002_scraped_data_age_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='cash_flow_multiple',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraped_data',
            name='cash_flow_multiple',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
