# Generated by Django 4.2.9 on 2024-09-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0003_archives_cash_flow_multiple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='email_preference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emailverified',
            field=models.BooleanField(default=False),
        ),
    ]
