# Generated by Django 4.2.9 on 2024-09-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0004_lists_email_preference_user_emailverified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lists',
            new_name='List',
        ),
    ]
