# Generated by Django 4.2.9 on 2024-09-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0005_rename_lists_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('last_run_date', models.DateTimeField(auto_now_add=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('total_listing_scrapped', models.IntegerField(blank=True, null=True)),
                ('new_listing_scrapped', models.IntegerField(blank=True, null=True)),
                ('old_listing_deleted', models.IntegerField(blank=True, null=True)),
                ('listine_for_review', models.IntegerField(blank=True, null=True)),
                ('fields_scraped', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
