# Generated by Django 4.2.9 on 2024-09-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0006_script'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='listine_for_review',
            new_name='listing_for_review',
        ),
        migrations.AddField(
            model_name='list',
            name='email_frequecy',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='last_run_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
