# Generated by Django 4.2.9 on 2024-09-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0007_rename_listine_for_review_script_listing_for_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='email_frequecy',
        ),
        migrations.AddField(
            model_name='list',
            name='email_frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
