# Generated by Django 4.2.9 on 2024-10-01 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0009_list_email_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='next_email_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='schedule_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('login', models.TextField(blank=True, max_length=255, null=True)),
                ('db_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
