# Generated by Django 4.2.9 on 2024-10-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0010_list_next_email_date_script_schedule_at_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='db_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
