# Generated by Django 4.2.9 on 2024-10-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0011_alter_config_db_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='schedule_frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='schedule_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
