# Generated by Django 4.2.9 on 2024-10-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0012_script_schedule_frequency_alter_script_schedule_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='schedule_at',
            new_name='schedule_once',
        ),
        migrations.AddField(
            model_name='script',
            name='monthly_dates',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='schedule_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='schedule_days',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
