# Generated by Django 4.2.9 on 2024-10-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0013_rename_schedule_at_script_schedule_once_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='login',
        ),
        migrations.AddField(
            model_name='config',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='port',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
