# Generated by Django 4.2.9 on 2024-10-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0015_rename_schedule_days_script_schedule_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='age_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archives',
            name='first_scraped_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
