# Generated by Django 4.2.9 on 2024-10-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0016_archives_age_years_archives_first_scraped_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='user_filters',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
