# Generated by Django 4.2.9 on 2025-02-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0017_list_user_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='inventory_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archives',
            name='lease_expiration_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archives',
            name='rent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scraped_data',
            name='inventory_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scraped_data',
            name='lease_expiration_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scraped_data',
            name='rent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
