# Generated by Django 4.2.9 on 2025-02-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0018_archives_inventory_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='inventory_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archives',
            name='lease_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archives',
            name='rent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scraped_data',
            name='inventory_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scraped_data',
            name='lease_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scraped_data',
            name='rent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
