# Generated by Django 4.2.9 on 2025-02-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0019_alter_archives_inventory_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='filters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='user_filters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
