# Generated by Django 4.2.9 on 2025-02-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0021_archives_industry_archives_inventory_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraped_data',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
